### ISSUE TITLE
query for the code

### ISSUE THREAD

**Issue by BoYangXDU** [lcx20001012/GODSNCR#1]
Hi chenxing，

Thanks for your contribution to hyperspectral target detection.  It's a nice work.
I am keen to explore your code implementation to further my understanding and potentially apply it to my own research as a comparison method.
However, it has not been released yet. 
Can you tell me about your plans for code release if it is possible？
Thanks ：）

**Comment by Chenxing-Li** [comment]
I am very pleased with your recognition of my work and I will release the code as soon as possible by next week.
Thanks ：）



At 2024-04-16 19:04:10, "BoYangXDU" ***@***.***> wrote:

Hi chenxing，

Thanks for your contribution to hyperspectral target detection. It's a nice work.
I am keen to explore your code implementation to further my understanding and potentially apply it to my own research as a comparison method.
However, it has not been released yet.
Can you tell me about your plans for code release if it is possible？
Thanks ：）

**Comment by BoYangXDU** [comment]
Thank you very much for promptly releasing the code !!!!
